version: '1'

services:
  app:
    image: tu-pedido-ya:local
    container_name: tu-pedido-ya-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app


